// Generated by gencpp from file husky_high_level_controller/StartStopBot.msg
// DO NOT EDIT!


#ifndef HUSKY_HIGH_LEVEL_CONTROLLER_MESSAGE_STARTSTOPBOT_H
#define HUSKY_HIGH_LEVEL_CONTROLLER_MESSAGE_STARTSTOPBOT_H

#include <ros/service_traits.h>


#include <husky_high_level_controller/StartStopBotRequest.h>
#include <husky_high_level_controller/StartStopBotResponse.h>


namespace husky_high_level_controller
{

struct StartStopBot
{

typedef StartStopBotRequest Request;
typedef StartStopBotResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StartStopBot
} // namespace husky_high_level_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::husky_high_level_controller::StartStopBot > {
  static const char* value()
  {
    return "09fb03525b03e7ea1fd3992bafd87e16";
  }

  static const char* value(const ::husky_high_level_controller::StartStopBot&) { return value(); }
};

template<>
struct DataType< ::husky_high_level_controller::StartStopBot > {
  static const char* value()
  {
    return "husky_high_level_controller/StartStopBot";
  }

  static const char* value(const ::husky_high_level_controller::StartStopBot&) { return value(); }
};


// service_traits::MD5Sum< ::husky_high_level_controller::StartStopBotRequest> should match
// service_traits::MD5Sum< ::husky_high_level_controller::StartStopBot >
template<>
struct MD5Sum< ::husky_high_level_controller::StartStopBotRequest>
{
  static const char* value()
  {
    return MD5Sum< ::husky_high_level_controller::StartStopBot >::value();
  }
  static const char* value(const ::husky_high_level_controller::StartStopBotRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::husky_high_level_controller::StartStopBotRequest> should match
// service_traits::DataType< ::husky_high_level_controller::StartStopBot >
template<>
struct DataType< ::husky_high_level_controller::StartStopBotRequest>
{
  static const char* value()
  {
    return DataType< ::husky_high_level_controller::StartStopBot >::value();
  }
  static const char* value(const ::husky_high_level_controller::StartStopBotRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::husky_high_level_controller::StartStopBotResponse> should match
// service_traits::MD5Sum< ::husky_high_level_controller::StartStopBot >
template<>
struct MD5Sum< ::husky_high_level_controller::StartStopBotResponse>
{
  static const char* value()
  {
    return MD5Sum< ::husky_high_level_controller::StartStopBot >::value();
  }
  static const char* value(const ::husky_high_level_controller::StartStopBotResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::husky_high_level_controller::StartStopBotResponse> should match
// service_traits::DataType< ::husky_high_level_controller::StartStopBot >
template<>
struct DataType< ::husky_high_level_controller::StartStopBotResponse>
{
  static const char* value()
  {
    return DataType< ::husky_high_level_controller::StartStopBot >::value();
  }
  static const char* value(const ::husky_high_level_controller::StartStopBotResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HUSKY_HIGH_LEVEL_CONTROLLER_MESSAGE_STARTSTOPBOT_H
