// Generated by gencpp from file husky_high_level_controller/StartStopBotResponse.msg
// DO NOT EDIT!


#ifndef HUSKY_HIGH_LEVEL_CONTROLLER_MESSAGE_STARTSTOPBOTRESPONSE_H
#define HUSKY_HIGH_LEVEL_CONTROLLER_MESSAGE_STARTSTOPBOTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace husky_high_level_controller
{
template <class ContainerAllocator>
struct StartStopBotResponse_
{
  typedef StartStopBotResponse_<ContainerAllocator> Type;

  StartStopBotResponse_()
    : success(false)
    , message()  {
    }
  StartStopBotResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::husky_high_level_controller::StartStopBotResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::husky_high_level_controller::StartStopBotResponse_<ContainerAllocator> const> ConstPtr;

}; // struct StartStopBotResponse_

typedef ::husky_high_level_controller::StartStopBotResponse_<std::allocator<void> > StartStopBotResponse;

typedef boost::shared_ptr< ::husky_high_level_controller::StartStopBotResponse > StartStopBotResponsePtr;
typedef boost::shared_ptr< ::husky_high_level_controller::StartStopBotResponse const> StartStopBotResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::husky_high_level_controller::StartStopBotResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::husky_high_level_controller::StartStopBotResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::husky_high_level_controller::StartStopBotResponse_<ContainerAllocator1> & lhs, const ::husky_high_level_controller::StartStopBotResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::husky_high_level_controller::StartStopBotResponse_<ContainerAllocator1> & lhs, const ::husky_high_level_controller::StartStopBotResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace husky_high_level_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::husky_high_level_controller::StartStopBotResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::husky_high_level_controller::StartStopBotResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::husky_high_level_controller::StartStopBotResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::husky_high_level_controller::StartStopBotResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::husky_high_level_controller::StartStopBotResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::husky_high_level_controller::StartStopBotResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::husky_high_level_controller::StartStopBotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::husky_high_level_controller::StartStopBotResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::husky_high_level_controller::StartStopBotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "husky_high_level_controller/StartStopBotResponse";
  }

  static const char* value(const ::husky_high_level_controller::StartStopBotResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::husky_high_level_controller::StartStopBotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string message\n"
"\n"
;
  }

  static const char* value(const ::husky_high_level_controller::StartStopBotResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::husky_high_level_controller::StartStopBotResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StartStopBotResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::husky_high_level_controller::StartStopBotResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::husky_high_level_controller::StartStopBotResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HUSKY_HIGH_LEVEL_CONTROLLER_MESSAGE_STARTSTOPBOTRESPONSE_H
