// Generated by gencpp from file husky_high_level_controller/StartStopBotRequest.msg
// DO NOT EDIT!


#ifndef HUSKY_HIGH_LEVEL_CONTROLLER_MESSAGE_STARTSTOPBOTREQUEST_H
#define HUSKY_HIGH_LEVEL_CONTROLLER_MESSAGE_STARTSTOPBOTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace husky_high_level_controller
{
template <class ContainerAllocator>
struct StartStopBotRequest_
{
  typedef StartStopBotRequest_<ContainerAllocator> Type;

  StartStopBotRequest_()
    : data(false)  {
    }
  StartStopBotRequest_(const ContainerAllocator& _alloc)
    : data(false)  {
  (void)_alloc;
    }



   typedef uint8_t _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::husky_high_level_controller::StartStopBotRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::husky_high_level_controller::StartStopBotRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StartStopBotRequest_

typedef ::husky_high_level_controller::StartStopBotRequest_<std::allocator<void> > StartStopBotRequest;

typedef boost::shared_ptr< ::husky_high_level_controller::StartStopBotRequest > StartStopBotRequestPtr;
typedef boost::shared_ptr< ::husky_high_level_controller::StartStopBotRequest const> StartStopBotRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::husky_high_level_controller::StartStopBotRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::husky_high_level_controller::StartStopBotRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::husky_high_level_controller::StartStopBotRequest_<ContainerAllocator1> & lhs, const ::husky_high_level_controller::StartStopBotRequest_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::husky_high_level_controller::StartStopBotRequest_<ContainerAllocator1> & lhs, const ::husky_high_level_controller::StartStopBotRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace husky_high_level_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::husky_high_level_controller::StartStopBotRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::husky_high_level_controller::StartStopBotRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::husky_high_level_controller::StartStopBotRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::husky_high_level_controller::StartStopBotRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::husky_high_level_controller::StartStopBotRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::husky_high_level_controller::StartStopBotRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::husky_high_level_controller::StartStopBotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8b94c1b53db61fb6aed406028ad6332a";
  }

  static const char* value(const ::husky_high_level_controller::StartStopBotRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8b94c1b53db61fb6ULL;
  static const uint64_t static_value2 = 0xaed406028ad6332aULL;
};

template<class ContainerAllocator>
struct DataType< ::husky_high_level_controller::StartStopBotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "husky_high_level_controller/StartStopBotRequest";
  }

  static const char* value(const ::husky_high_level_controller::StartStopBotRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::husky_high_level_controller::StartStopBotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool data\n"
;
  }

  static const char* value(const ::husky_high_level_controller::StartStopBotRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::husky_high_level_controller::StartStopBotRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StartStopBotRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::husky_high_level_controller::StartStopBotRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::husky_high_level_controller::StartStopBotRequest_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HUSKY_HIGH_LEVEL_CONTROLLER_MESSAGE_STARTSTOPBOTREQUEST_H
